database:
  adapter: mysql
  database: gozen
  username: gozen
  password: rootpass
  host: 127.0.0.1
  port: 3306


oauth:
  after_oauth_url: http://example.com
  github:
    client_id:
    client_secret:
  google:
    client_id:
    client_secret:
    redirect_url: http://api.gozen.com:9000/oauth/google_cb
  facebook:
    client_id:
    client_secret:
    redirect_url: http://api.gozen.com:9000/oauth/facebook_cb


log:
  verbose: true
  file_path: /var/work/src/gozen/gozen.log